### ISSUE TITLE
Merging back to WyattBlue's fork

### ISSUE THREAD

**Issue by AtilioA** [seaty6/jumpcutterV2#5]
Do you plan PRing this fork back to WyattBlue's? There has been some recent commits on that one and I don't think maintaining the GUI would be a problem. This fork might get outdated to the point I'd prefer to just use the CLI.

**Comment by seaty6** [comment]
Sorry for getting back to you so late - I think WyattBlue has moved his implementation of this to his [Auto Editor](https://github.com/WyattBlue/auto-editor) project. It doesn't have a GUI, but its different feature set seems like its more used for editing videos, rather than mine which was used to process folders of lectures.

**Comment by AtilioA** [comment]
Actually, I've been using auto-editor for lectures and it's great! If I have multiple files, I just write a one-liner in the terminal for that.
